name: cargo
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.24+25

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  easy_localization: ^3.0.2
  get_it: ^7.6.0
  shared_preferences: ^2.1.2
  after_layout: ^1.2.0
  rect_getter: ^1.1.0
  conditional_builder_null_safety: ^0.0.6
  bloc: ^7.0.0
  url_launcher: ^6.1.11
  smooth_page_indicator: ^1.1.0
  shimmer: ^2.0.0
#  infinity_page_view: ^1.0.0
  http: ^0.13.3
  http_interceptor: ^0.4.1
  dio: ^4.0.0
  dartz: ^0.10.1
  flutter_hex_color: ^2.0.0
  flutter_bloc: ^7.0.0
  flutter_svg: ^2.0.7
  fluttertoast: ^8.0.7
  font_awesome_flutter: ^9.0.0
  dots_indicator: ^2.0.0
  google_maps_place_picker_mb: ^3.0.2
  geolocator: ^9.0.2
  path_provider: ^2.0.2
  align_positioned: ^2.0.1
  expandable: ^5.0.1
  qr_code_scanner: ^1.0.1
  firebase_messaging: ^14.6.1
  firebase_core: ^2.13.0
  flutter_launcher_icons: ^0.13.1
  connectivity: ^3.0.6
  flash: ^1.2.0
  permission_handler: ^6.0.1+1
  change_app_package_name: ^1.0.0
  pull_to_refresh: ^2.0.0
  timeago: ^3.1.0
  rename: ^2.1.1
  app_tracking_transparency: ^2.0.3
  collection: ^1.17.1

dev_dependencies:
#  flutter_test:
#    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/langs/en.json
    - assets/langs/ar.json
    - assets/config.json
    - assets/images/
    - assets/icons/
    - assets/anim/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-BoldItalic.ttf
          weight: 800
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
