name: Build Android APK

on:
  workflow_dispatch:
    inputs:
      project-dir:
        description: 'مسار مشروع Flutter بالنسبة لجذر المستودع'
        required: true
        default: '.'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show tree
        run: |
          echo "Root files:"
          ls -la
          echo "Project dir files:"
          ls -la "${{ github.event.inputs['project-dir'] }}"

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter (stable)
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Flutter pub get
        working-directory: ${{ github.event.inputs['project-dir'] }}
        run: flutter pub get

      # لو عندك google-services.json أضفه قبل البناء (اختياري)
      # - name: Copy google-services.json
      #   run: |
      #     mkdir -p ${{ github.event.inputs['project-dir'] }}/android/app
      #     echo "$GOOGLE_SERVICES_JSON" > ${{ github.event.inputs['project-dir'] }}/android/app/google-services.json
      #   env:
      #     GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}

      - name: Build APK (release)
        working-directory: ${{ github.event.inputs['project-dir'] }}
        run: flutter build apk --release --no-tree-shake-icons

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ${{ github.event.inputs['project-dir'] }}/build/app/outputs/flutter-apk/app-release.apk
