name: Build Android APK

on:
  workflow_dispatch:

env:
  PROJECT_DIR: a   # <-- غيّر الاسم لو مختلف

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show tree
        run: |
          echo "Root files:"
          ls -la
          echo "Project dir files:"
          ls -la $PROJECT_DIR

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'
          channel: 'stable'
          cache: true

      - name: Flutter pub get
        working-directory: ${{ env.PROJECT_DIR }}
        run: flutter pub get

      # (اختياري) لو عايز تتأكد من gradlew موجود
      - name: Make gradlew executable (if exists)
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          if [ -f android/gradlew ]; then
            chmod +x android/gradlew
          fi

      - name: Build debug APK
        working-directory: ${{ env.PROJECT_DIR }}
        run: flutter build apk --debug

      - name: Build release APK
        working-directory: ${{ env.PROJECT_DIR }}
        run: flutter build apk --release --no-shrink

      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: ${{ env.PROJECT_DIR }}/build/app/outputs/flutter-apk/app-debug.apk

      - name: Upload release APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ${{ env.PROJECT_DIR }}/build/app/outputs/flutter-apk/app-release.apk
