name: Build Android APK

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'

      - name: Set up Flutter 2.10.5
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.5'
          channel: 'stable'
          cache: true

      - name: Pin Gradle to 7.2 (compatible with Flutter 2.10.5)
        run: |
          sed -i 's#distributionUrl=.*#distributionUrl=https\://services.gradle.org/distributions/gradle-7.2-bin.zip#' android/gradle/wrapper/gradle-wrapper.properties || true
          cat android/gradle/wrapper/gradle-wrapper.properties

      # إذا كان عندك google-services.json ضعه في android/app/ قبل البناء
      # لو ما هو مرفوع في المستودع، احذِف الخطوتين الجايتين:
      - name: Ensure google-services.json exists (skip if already committed)
        run: |
          if [ ! -f android/app/google-services.json ]; then
            echo "WARNING: android/app/google-services.json not found. Push it or skip Firebase."
          fi

      - name: Flutter pub get
        run: flutter pub get

      - name: Build debug APK (no shrink)
        run: flutter build apk --debug --no-shrink

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: build/app/outputs/flutter-apk/app-debug.apk
